// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using test_web_empty;

namespace test_web_empty.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210221113349_ChangeRequiredAttributes")]
    partial class ChangeRequiredAttributes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("test_web_empty.TCameraGroups", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDetected")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CameraGroups");
                });

            modelBuilder.Entity("test_web_empty.TCameras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CameraGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("CameraGroupsId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDetected")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CameraGroupsId");

                    b.ToTable("Cameras");
                });

            modelBuilder.Entity("test_web_empty.TCameras", b =>
                {
                    b.HasOne("test_web_empty.TCameraGroups", "CameraGroups")
                        .WithMany("Cameras")
                        .HasForeignKey("CameraGroupsId");

                    b.Navigation("CameraGroups");
                });

            modelBuilder.Entity("test_web_empty.TCameraGroups", b =>
                {
                    b.Navigation("Cameras");
                });
#pragma warning restore 612, 618
        }
    }
}
